[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = ['python']
merged=0
reve="release"
hock_add = '''
   "coc-emmet"
'''    

[[plugins]]
repo = 'rust-lang/rust.vim'
hock_add = '''
   let g:rustfmt_autosave = 1 
'''


[[plugins]]
repo = 'rust-lang/rustfmt'
hock_add = '''
   let g:rustfmt_autosave = 1
'''


[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'preservim/nerdtree'
hock_add = '''
   let g:NERDTreeShowHidden=1
'''
