[[plugins]]
repo = 'preservim/nerdtree'
hock_add = '''
   "NERDtree
   let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'mattn/vim-molder'
hock_add = '''
   let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hock_add = '''
   " Color Scheame
   set termguicolors
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hock_add = '''
   set hlg=ja,en
'''

[[plugins]]
repo = 'YukiYuigishi/memo.vim'
hock_add = '''
 let g:memo_saved_dir = '$HOME/memo'
 let g:memo_preview=0
'''

[[plugins]]
repo = 'vimwiki/vimwiki'
hock_add = '''

let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jiangmaio/auto-pairs'
