[[plugins]]
repo = 'preservim/nerdtree'
hock_add = '''
   "NERDtree
   let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'mattn/vim-molder'
hock_add = '''
   let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hock_add = '''
   " Color Scheame
   set termguicolors
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hock_add = '''
   set hlg=ja,en
'''
