[[plugins]]
repo = 'preservim/nerdtree'
hock_add = '''
   "NERDtree
   let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'mattn/vim-molder'
hock_add = '''
   let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hock_add = '''
   set termguicolors
'''

[[plugins]]
repo = 'sudar/vim-arduino-syntax'
merged=0
reve="release"

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hock_add = '''
   set hlg=ja,en
'''

[[plugins]]
repo = 'YukiYuigishi/memo.vim'
hock_add = '''
 let g:memo_saved_dir = '$HOME/memo'
 let g:memo_preview=0
'''
